# Generated by Django 5.0.14 on 2026-07-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='responsavel_obrigatorio',
            field=models.BooleanField(default=False, help_text='Se marcado, é obrigatório escolher um responsável específico deste departamento ao criar Tarefas/Ações; senão, qualquer um dos responsáveis cadastrados pode atender.'),
        ),
    ]
