# Generated by Django 5.0.14 on 2026-07-03 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorCaiFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_fiscal', models.CharField(max_length=10, unique=True)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de CAI Fiscal',
                'verbose_name_plural': 'Contadores de CAI Fiscal',
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano_fiscal', models.CharField(db_index=True, max_length=10)),
                ('numero_sequencial', models.PositiveIntegerField(editable=False)),
                ('cai_fiscal', models.CharField(blank=True, editable=False, help_text="Gerado automaticamente (ex: 51 / 25'26).", max_length=30, unique=True)),
                ('data_criacao', models.DateField(db_index=True)),
                ('data_cai', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('INTRODUCAO', 'Introdução'), ('ALTERACAO', 'Alteração')], max_length=15)),
                ('revisao', models.CharField(blank=True, max_length=50)),
                ('cliente', models.CharField(db_index=True, max_length=150)),
                ('numero_projeto', models.CharField(max_length=100)),
                ('comentarios', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('APROVADO_COM_ACOES', 'Aprovado com ações'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cancela_comunicado', models.ForeignKey(blank=True, help_text='Outro Comunicado que este CAI cancela, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelado_por', to='comunicados.comunicado')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('departamento_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados_solicitados', to='core.departamento')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-data_criacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ComunicadoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='comunicados/anexos/%Y/%m/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='comunicados.comunicado')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
        migrations.AddConstraint(
            model_name='comunicado',
            constraint=models.UniqueConstraint(fields=('ano_fiscal', 'numero_sequencial'), name='unique_numero_sequencial_por_ano_fiscal'),
        ),
    ]
