# Generated by Django 5.0.14 on 2026-07-11 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contadorcaifiscal',
            options={'verbose_name': 'Contador de Numeração Fiscal', 'verbose_name_plural': 'Contadores de Numeração Fiscal'},
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='cancela_comunicado',
            field=models.ForeignKey(blank=True, help_text='Outro Comunicado que este substitui, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelado_por', to='comunicados.comunicado'),
        ),
    ]
