# Generated by Django 5.0.14 on 2026-07-03 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20)),
                ('prazo_original', models.DateField(db_index=True)),
                ('prazo_reajustado', models.DateField(blank=True, help_text='Quando preenchido, prevalece sobre o prazo original no cálculo de atraso.', null=True)),
                ('responsavel_nome', models.CharField(blank=True, max_length=150)),
                ('data_inclusao', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['prazo_original'],
            },
        ),
    ]
