# Generated by Django 5.0.14 on 2026-07-03 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acoes', '0001_initial'),
        ('comunicados', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='comunicado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='comunicados.comunicado'),
        ),
        migrations.AddField(
            model_name='acao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acao',
            name='departamento',
            field=models.ForeignKey(help_text='Herdado da Tarefa de origem; preenchido automaticamente ao salvar.', on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='core.departamento'),
        ),
        migrations.AddField(
            model_name='acao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
