# Generated by Django 5.0.14 on 2026-07-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0004_acaoanexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
